### ISSUE TITLE
Colours in Dark Mode v2.2.3

### ISSUE THREAD

**Issue by CCV54** [1to9only/HoDoKu#10]
@1to9only So far I notice some colours not as discussed for the Dark version. 
Background/ALS should be:-
Normal: 240, 240, 240
Selection: xxx, xxx, xxx
Forbidden: 164, 173, 191
Possible: 193, 204, 219
Altern: 240, 240, 240

COLORKU_COLORS should be:-
1. 245, 28, 47
2. 255, 144, 0
3. 222, 199, 0
4. xxx, xxx, xxx
5. 3, 224, 111
6. 0, 181, 205
7. 11, 60, 225
8. 160, 6, 245
9. 228, 0, 196

**Comment by 1to9only** [comment]
See: https://github.com/1to9only/HoDoKu/issues/6#issuecomment-942704509
Which resulted in the colors listed in https://github.com/CCV54/HoDoKu/releases/tag/2.2.2 to be used.
I also posted https://github.com/1to9only/HoDoKu/files/7343754/color.changes.dark.mode.txt
The colors are correct.

**Comment by CCV54** [comment]
[] COLORKU_COLORS = {
1:              new Color(234,  26,  45),   // 1                                        245,  28,  47
2:              new Color(255, 147,   0),   // 2                                        255, 144,   0
3:              new Color(220, 205,   0),   // 3                                        222, 199,   0
4:              new Color( 63, 205,   0),   // 4                                         62, 205,   0
5:              new Color(  4, 230, 115),   // 5                                          3, 224, 111
6:              new Color(  0, 193, 219),   // 6                                          0, 181, 205
7:              new Color( 10,  58, 225),   // 7                                         11,  60, 225
8:              new Color(151,   0, 239),   // 8                                        160,   6, 245
9:              new Color(230,   2, 204),   // 9                                        228,   0, 196

These changes are not reflected in HoDoKu-Dark.

**Comment by CCV54** [comment]
Actually, some of the default colours in standard HoDoKu mode aren't exactly what I wanted.
