### ISSUE TITLE
Save Puzzle Error

### ISSUE THREAD

**Issue by CCV54** [1to9only/HoDoKu#13]
This is from the windows installer version:

![Save_Puzzle_Error](https://user-images.githubusercontent.com/26049501/138371838-1383120a-8853-4094-8a37-d938feb558c0.jpg)

It saved a puzzle file once, but now it won't Save Puzzle again (i.e., overwrite existing file) nor will it Save Puzzle As... again by any other name without producing the same error.

After navigating back to the old default location, user home, it's working fine.

**Comment by 1to9only** [comment]
If Hodoku is installed in:
- Program Files
- Program Files (x86)

the file folder reverts back to the user home folder (as it was before).

When installing Hodoku, the user can install Hodoku in another location (e.g. C:\HoDoKu), then the file folder is the HoDoKu install location.

I have tested this.

Note that you may still be able to install HoDoKu in a Windows System folder (e.g. C:\Windows\HoDoKu), then you are a Windows expert able to fix this with ease!!

**Comment by CCV54** [comment]
Hi @1to9only, I wasn't thinking of taking my work to a next version. Maybe the Filter digits could do with some attention, especially being made larger for HD displays... Not sure I want to rework the ColorKu mask, but the possibility remains open.
I'm a bit sick and tired of it, tbh..

What makes me really very happy is to see my efforts come to fruition in **_your_** v2.2.4! Haven't tested the installer yet, but your notes are reassuring, I've always appreciated your help, since my abilities go only so far. Many thanks again!

Cheers,

Colin.
