### ISSUE TITLE
Another New Look for HoDoKu.

### ISSUE THREAD

**Issue by CCV54** [1to9only/HoDoKu#9]
Redrawn Icons mostly, and some further colour changes. It never will be 'finished', but _I am_!

[HoDoKu[v2.2.3].jar.zip](https://github.com/1to9only/HoDoKu/files/7356631/HoDoKu.v2.2.3.jar.zip)

Proposed Colour changes include _some_ of these:

Borders and Digits
Values: 0, 102, 102
Canidates: 100, 100, 100 ✓

Hints
Normal 43, 216, 93
Fins 117, 180, 255

Background/ALS
Normal: 245, 245, 245
Selection: 255:255:150
Forbidden: 175, 189, 196
Possible: 198, 213, 220
Altern.: 245, 245, 245

Pen A:  (1) 234, 149, 0 (2) 255, 191, 73
Pen B: (1) 169, 123, 254 (2) 197, 168, 248

ColorKu:

Invalid. 20, 30, 40

1. 245, 28, 49
2. 255, 150, 0
3. 222, 203, 0
4. 62, 205, 0 ✓
5. 3, 226, 112
6. 0, 184, 209
7. 11, 58, 225
8. 158, 5, 245
9. 235, 2, 204

Perhaps changes could be included in #7?

**Comment by 1to9only** [comment]
> Redrawn Icons mostly, and some further colour changes. It never will be 'finished', but _I am_!

I can extract the images from the jar file. A list would be helpful, but not really needed, as I'll figure out what's changed, it just takes time, and everything else gets pushed forward.

> Proposed Colour changes include _some_ of these:

Are there more??

**Comment by CCV54** [comment]
abortHint, ce-20, concreteHint, executeHint, all Filter digits both active and inactive, inactive (for ColorKu), a number of "invalid" files, but the program uses only invalid20, listview16 and 16b, nextHint, ov078, redo. rgDeselected, rgSelected, search_c1, _d1, _e1, _s1 and _t1, treeview16 and 16b, undo and vageHint.

hth 

(Guessing the same list for the Dark version, although the are mostly quite different images in that case.

No more colour changes. Actually, likely a little fewer since I'm fairly certain there are some unchanged but lost track of which they might be.

Oh, and, I forgot:

[icons-readme.txt](https://github.com/1to9only/HoDoKu/files/7358287/icons-readme.txt)

**Comment by 1to9only** [comment]
@CCV54, the Filter.zip contains 1-9 and xy images. Can you package the 5 icons in the previous post in a zip file - this will save me time downloading them individually, and matching them to the correct image file name.

**Comment by CCV54** [comment]
@1to9only Thank you. I see now what you mean.

[Hint-buttons.zip](https://github.com/1to9only/HoDoKu/files/7360728/Hint-buttons.zip)
